# Generated by Django 5.2.12 on 2026-03-10 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="authored_surveys",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="api.survey",
                verbose_name="Опрос",
            ),
        ),
        migrations.AddField(
            model_name="surveysession",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="api.survey",
                verbose_name="Опрос",
            ),
        ),
        migrations.AddField(
            model_name="surveysession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="survey_sessions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.surveysession",
                verbose_name="Сеанс",
            ),
        ),
        migrations.AddIndex(
            model_name="choice",
            index=models.Index(
                fields=["question", "order"], name="api_choice_questio_4ec120_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["survey", "order"], name="api_questio_survey__f65b86_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="surveysession",
            constraint=models.UniqueConstraint(
                fields=("survey", "user"), name="unique_survey_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="answer",
            constraint=models.UniqueConstraint(
                fields=("session", "question"), name="unique_session_question"
            ),
        ),
    ]
