# Generated by Django 5.2.12 on 2026-03-11 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="answered_at",
        ),
    ]
